### ISSUE TITLE
api.obfs.dev rate limit

### ISSUE THREAD

**Issue by daydreamer-json** [Tsuk1ko/heroku-pximg-proxy#8]
I frequently get rate-limit errors with the api.obfs.dev API, is there a way to use the Pixiv Ajax API?

**Comment by Tsuk1ko** [comment]
Well, actually I just switched from the Ajax API. 8a567d25163ec524ae6634d0083af6a3eb392a2a

At that day I found the Pixiv Ajax API was limited when used anonymously. `urls` will become `null`.

![image](https://user-images.githubusercontent.com/24877906/212530726-c93a0367-39d5-4d3c-b42f-2f63dda64258.png)

I tried to provide cookie but it will trigger Cloudflare js challenge.

api.obfs.dev use Pixiv Client API which like https://github.com/alphasp/pixiv-api-client. This can be used by yourself, but because of the complex problem of login status, it is not user-friendly for both deployment and use.

~So I think maybe I can continue use Pixiv Ajax API, but I must guess the file extension (only needed for origin image url). Try in `jpg` and `png` should be fine.~

**Comment by Tsuk1ko** [comment]
Bad news. The Ajax API don't give the seconds of date so it is impossible to splice urls.

![image](https://user-images.githubusercontent.com/24877906/212534964-378dd288-9e33-4ba6-ab02-7228efef0d12.png)

I can only try to provide a tool to get `refreshToken` and using client API.

**Comment by Tsuk1ko** [comment]
Now you can provide `refreshToken`, see readme.
